version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=projectvil
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=IdentityDb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=projectvil@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=1234567890
    ports:
      - "5052:80"

  web_gateway:
    build:
      context: /WebGateway
      dockerfile: Dockerfile
    container_name: web_gateway
    ports:
      - '5093:80'
      - '7250:443'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro   
    depends_on:
      - postgres
