version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=projectvil
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=IdentityDb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=projectvil@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=1234567890
    ports:
      - "5052:80"